csp: ${cloud-platform}
compartment_id: ${project}
zone: ${zone}
network_name: ${network_name}
subnet: ${subnet}
subnet_name: ${subnet_name}
ansible_repo: ${ansible_repo}
ansible_branch: ${ansible_branch}
cluster_id: ${cluster_id}
