#!/bin/bash

date

echo milliams

yum install -y ansible git
cat > /root/hosts <<EOF
[management]
$(hostname -f)
EOF

time python -u /usr/bin/ansible-pull --url=https://github.com/ACRC/slurm-ansible-playbook.git --checkout=${ansible_branch} --inventory=/root/hosts --extra-vars="compartment_ocid=${compartment_ocid}" management.yml >> /root/ansible-pull.log

date
